version: '3.8'

services:
  # Database service
  db:
    image: mariadb:10.11
    container_name: school-attendance-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-school_attendance}
      MYSQL_USER: ${DB_USER:-attendance_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-attendance_pass}
    volumes:
      - db_data:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      - school-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: school-attendance-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Database configuration
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/${DB_NAME:-school_attendance}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-attendance_user}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-attendance_pass}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      
      # JPA/Hibernate configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: ${SHOW_SQL:-false}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MariaDBDialect
      
      # Email configuration
      SPRING_MAIL_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SPRING_MAIL_PORT: ${SMTP_PORT:-587}
      SPRING_MAIL_USERNAME: ${SMTP_USERNAME}
      SPRING_MAIL_PASSWORD: ${SMTP_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      
      # Twilio configuration for SMS
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      
      # Security
      SPRING_SECURITY_USER_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      
      # Application configuration
      SERVER_PORT: 8080
      JAVA_OPTS: "-Xmx512m -Xms256m"
    ports:
      - "8080:8080"
    networks:
      - school-network
    volumes:
      - backend_logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: school-attendance-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:8080/api}
      REACT_APP_ENV: ${REACT_APP_ENV:-production}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - school-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  school-network:
    driver: bridge
    name: school-attendance-network

volumes:
  db_data:
    driver: local
    name: school-attendance-db-data
  backend_logs:
    driver: local
    name: school-attendance-backend-logs
